### ISSUE TITLE
Difference between AngularIsoLoss and OCSoftmax ?

### ISSUE THREAD

**Issue by tcourat** [yzyouzhang/HBAS_chapter_voice3#2]
Hi,

I am not sure that I understand the difference between the two losses OCSoftmax and AngularIsoLoss. Can you clarify ? Thanks.

**Comment by yzyouzhang** [comment]
Thanks for your question! The angular isolate loss is to alleviate the imbalance between compacting the bonafide representation and isolating spoofing attacks from the OC-Softmax. Details are in the book chapter; see the screenshot below.
<img width="851" alt="image" src="https://github.com/user-attachments/assets/5e637ac8-0005-4624-986f-82ba19e30258">
